[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[[services]]
serviceName = "backend"
source = "."

[services.variables]
NODE_ENV = "production"
